### ISSUE TITLE
Change the name of the App

### ISSUE THREAD

**Issue by ingilniero** [philip13/agro_reports#18]
The current UI shows  "V-Dashboard" as the name of the app in the navigation sidebar.

- Change it to "AgroReports"
- Make a link pointing to the root path

<img width="130" alt="Screenshot 2023-03-21 at 13 07 23" src="https://user-images.githubusercontent.com/1796036/226715267-6b12ac24-c70b-41b7-9834-afe759c6c79d.png">

**Comment by philip13** [comment]
Why this issue is part of ui/ux, I am not familiarly with that concept to mouch

**Comment by ingilniero** [comment]
> Why is this issue labeled UI/UX, I am not familiar with that concept too much.

UI = User Interface
UX = User Experience

This particular issue talks about some parts of the UI that can be improved to make the UX better.
